<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>
	<a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/then">promise then的返回值</a>
	<script>
		let url = "http://fptxl.com/fptxl/hello";
		//我们封装了下promise
		function request(url) {
			return new Promise(function (resolve, reject) {
				// Standard XHR to load an image
				let xhr = new XMLHttpRequest();
				xhr.open("GET", url);
				xhr.onload = () => resolve(xhr.responseText);
				xhr.onerror = () => reject(xhr.statusText);
				xhr.send();
			});
		}
		//如果 then 中的回调函数返回值的几种场景：
		//1.返回了一个值，那么 then 返回的 Promise 将会成为接受状态，并且将返回的值作为接受状态的回调函数的参数值。
		var thenValueResult=request(url).then(function(value){
			console.log("1.then将这个值'"+value+"'返回");
			return value;
		})
		thenValueResult.then(function(value){
			console.log("1.上一个then返回一个值："+value);
		})

		//2.没有返回任何值，那么 then 返回的 Promise 将会成为接受状态，并且该接受状态的回调函数的参数值为 undefined。
		var thenNoReturn=request(url).then(function(value){
			console.log("2.then不返回这个值'"+value+"");
		})
		thenNoReturn.then(function(value){
			console.log("2.上一个then没有返回值：所以此处是undefined："+value);
		})

		//3.抛出一个错误，那么 then 返回的 Promise 将会成为拒绝状态，并且将抛出的错误作为拒绝状态的回调函数的参数值。
		var thenThrowError=request(url).then(function(value){
			console.log("3.1.then 抛出了一个错误");
			throw '3.1.then 抛出了一个错误';
			return value;
		})
		thenThrowError.then(function(value){
			console.log("3.1代码不会执行到这里"+value);
		},function(error){
			console.log("3.1then中的reject回调处理异常"+error);
		})


		var thenThrowError2=request(url).then(function(value){
			console.log("3.2.then 抛出了一个错误");
			throw '3.2.then 抛出了一个错误';
			return value;
		})
		thenThrowError2.catch(function(error){
			console.log("3.2.使用catch处理异常"+error);
		})

		//4.返回一个已经是接受状态的 Promise，那么 then 返回的 Promise 也会成为接受状态，
		// 并且将那个 Promise 的接受状态的回调函数的参数值作为该被返回的Promise的接受状态回调函数的参数值。

		//Promise.resolve(value)方法返回一个以给定值解析后的Promise 对象。
		Promise.resolve(1).then(function(value){
			console.log("4.then返回一个接受状态的Promise："+value+"");
		})



		//如果 promise 在一个相应的处理程序被绑定时就已经被兑现或被拒绝了，那么这个处理程序就会被调用


		//5.返回一个已经是拒绝状态的 Promise，那么 then 返回的 Promise 也会成为拒绝状态，
		// 并且将那个 Promise 的拒绝状态的回调函数的参数值作为该被返回的Promise的拒绝状态回调函数的参数值。

		//Promise.reject()方法返回一个带有拒绝原因的Promise对象。
		Promise.reject("this is a reject test").then(function(value){
			console.log("5.此处不可达："+value+"");
		},function(error){
			console.log("5.then返回一个接受状态的Promise"+error);
		})


		//6.返回一个未定状态（pending）的 Promise，那么 then 返回 Promise 的状态也是未定的，并且它的终态与那个 Promise 的终态相同；
		// 同时，它变为终态时调用的回调函数参数与那个 Promise 变为终态时的回调函数的参数是相同的。
		var thenReturnPromise=request(url).then(function(value){
			console.log("6.then返回一个Promise'"+value+"");
			return request(url)
		})
		thenReturnPromise.then(function(value){
			console.log("6.返回的Promise成为接受状态时返回的值："+value);
		})


	</script>

</body>
</html>